const jobs = [
  { id:1, order:1, company:"한화솔루션", logo:"H", color:"#263126", title:"태양광 소재 연구개발 인턴", type:"인턴", fields:["연구","실험"], location:"대전·세종·충청권", companyType:"대기업·중견기업", workMode:"출근", eligibility:["재학생","졸업예정자"], experience:"신입·무경력", major:"전공 무관", salary:"급여 있음", days:18, match:94, visual:"lab", description:"태양광 소재의 특성을 분석하고 실험 데이터를 정리합니다. 연구팀의 실험 과정을 가까이에서 경험하며 에너지 분야의 첫 커리어를 시작할 수 있습니다.", tags:["인턴","연구개발","실험"] },
  { id:2, order:2, company:"한국에너지기술연구원", logo:"K", color:"#202020", title:"에너지저장 연구실 연구원", type:"신입", fields:["연구","품질"], location:"대전·세종·충청권", companyType:"공기업·공공기관", workMode:"출근", eligibility:["졸업예정자","졸업자"], experience:"신입·무경력", major:"전공 무관", salary:"급여 있음", days:23, match:93, visual:"energy", description:"에너지저장 시스템의 성능을 측정하고 연구 결과를 기록합니다. 새로운 에너지 기술의 가능성을 직접 확인하는 연구 직무입니다.", tags:["신입","에너지저장","연구"] },
  { id:3, order:3, company:"두산에너빌리티", logo:"D", color:"#42515b", title:"발전설비 품질관리 신입", type:"신입", fields:["품질"], location:"영남권", companyType:"대기업·중견기업", workMode:"출근", eligibility:["졸업예정자","졸업자"], experience:"신입·무경력", major:"전공 무관", salary:"급여 있음", days:14, match:91, visual:"quality", description:"발전설비 품질 데이터를 확인하고 검사 결과를 관리합니다. 현장과 사무 업무를 함께 경험하며 품질관리의 기본을 배웁니다.", tags:["신입","품질관리","설비"] },
  { id:4, order:4, company:"SK E&S", logo:"SK", color:"#202020", title:"수소사업 전략기획 인턴", type:"인턴", fields:["연구"], location:"수도권", companyType:"대기업·중견기업", workMode:"하이브리드", eligibility:["재학생","졸업예정자"], experience:"신입·무경력", major:"전공 무관", salary:"급여 있음", days:12, match:88, visual:"experiment", description:"수소 산업 자료를 조사하고 사업 현황을 정리합니다. 에너지 전환의 흐름을 읽고 기획 업무를 경험할 수 있습니다.", tags:["인턴","수소","기획"] },
  { id:5, order:5, company:"한국가스공사", logo:"K", color:"#53644e", title:"친환경 에너지 실험 보조", type:"인턴", fields:["실험","품질"], location:"대전·세종·충청권", companyType:"공기업·공공기관", workMode:"출근", eligibility:["재학생","졸업예정자"], experience:"신입·무경력", major:"전공 무관", salary:"급여 있음", days:10, match:87, visual:"experiment", description:"친환경 에너지 설비의 실험을 보조하고 결과를 기록합니다. 실험실에서 팀과 함께 꼼꼼하게 일하는 경험을 쌓습니다.", tags:["인턴","친환경","실험"] },
  { id:6, order:6, company:"LG에너지솔루션", logo:"LG", color:"#3d3150", title:"배터리 공정 품질 신입", type:"신입", fields:["품질","실험"], location:"수도권", companyType:"대기업·중견기업", workMode:"출근", eligibility:["졸업예정자","졸업자"], experience:"신입·무경력", major:"전공 무관", salary:"급여 있음", days:9, match:86, visual:"quality", description:"배터리 공정의 품질 기준을 확인하고 개선 데이터를 관리합니다. 제품이 완성되는 과정을 가까이에서 배우는 직무입니다.", tags:["신입","배터리","품질"] },
  { id:7, order:7, company:"에코프로", logo:"E", color:"#3c5248", title:"이차전지 소재 생산관리", type:"신입", fields:["품질"], location:"영남권", companyType:"스타트업·중소기업", workMode:"출근", eligibility:["졸업예정자","졸업자"], experience:"신입·무경력", major:"전공 무관", salary:"급여 있음", days:5, match:83, visual:"energy", description:"이차전지 소재 생산 데이터를 관리하고 공정 품질을 확인합니다.", tags:["신입","소재","생산관리"] },
  { id:8, order:8, company:"그린랩스", logo:"G", color:"#6c6b35", title:"탄소 데이터 분석 인턴", type:"인턴", fields:["연구"], location:"수도권", companyType:"스타트업·중소기업", workMode:"하이브리드", eligibility:["재학생","졸업예정자"], experience:"신입·무경력", major:"전공 무관", salary:"급여 있음", days:3, match:79, visual:"experiment", description:"탄소 배출 데이터를 모으고 환경 리포트 작성을 돕습니다.", tags:["인턴","탄소","데이터"] }
];

const state = { type:"전체", fields:new Set(), location:"전체", companyType:"전체", workMode:"전체", eligibility:"전체", deadlineOnly:true, savedOnly:false, query:"", view:"grid", saved:new Set(JSON.parse(localStorage.getItem("finder-saved") || "[]")) };
const $ = selector => document.querySelector(selector); const $$ = selector => [...document.querySelectorAll(selector)];
function fieldRank(job) { if (job.fields.includes("연구") && job.fields.includes("실험")) return 3; if (job.fields.includes("연구")) return 2; if (job.fields.includes("실험")) return 1; if (job.fields.includes("품질")) return 1; return 0; }
function filteredJobs() { const query=state.query.trim().toLowerCase(); return jobs.filter(job => { const text=[job.company,job.title,...job.fields,...job.tags].join(" ").toLowerCase(); return (state.type === "전체" || job.type === state.type) && (!state.fields.size || job.fields.some(field => state.fields.has(field))) && (state.location === "전체" || job.location === state.location) && (state.companyType === "전체" || job.companyType === state.companyType) && (state.workMode === "전체" || job.workMode === state.workMode) && (state.eligibility === "전체" || job.eligibility.includes(state.eligibility)) && (!state.deadlineOnly || job.days >= 7) && (!state.savedOnly || state.saved.has(job.id)) && (!query || text.includes(query)); }).sort((a,b) => fieldRank(b)-fieldRank(a) || a.order-b.order); }
function card(job,index) { const saved=state.saved.has(job.id); return `<article class="job-card" tabindex="0" data-id="${job.id}" style="animation-delay:${index*35}ms"><div class="card-header"><div class="company-mark"><span class="company-logo" style="background:${job.color}">${job.logo}</span><span>${job.company}</span></div><button class="bookmark ${saved ? "saved" : ""}" data-save="${job.id}" aria-label="${saved ? "저장 취소" : "공고 저장"}">${saved ? "★" : "☆"}</button></div><div class="card-copy"><p class="company-line">${job.type} · ${job.location}</p><h3 class="job-title">${job.title}</h3></div><div class="card-visual visual-${job.visual}"><span class="visual-word">${job.fields.join(" · ")}</span><span class="visual-number">0${job.id}</span></div><div class="card-tags">${job.tags.map(tag => `<span class="tag">${tag}</span>`).join("")}</div><div class="card-meta"><div class="meta-item"><span>지원 자격</span><b>${job.eligibility.join(" · ")}</b></div><div class="meta-item"><span>경력 · 전공</span><b>${job.experience} · ${job.major}</b></div><div class="meta-item"><span>근무 방식</span><b>${job.workMode}</b></div><div class="meta-item"><span>급여</span><b>${job.salary}</b></div></div><div class="card-footer"><span class="match">추천도 <b>${job.match}%</b></span><span class="deadline ${job.days<7 ? "soon" : ""}">D-${job.days}</span></div></article>`; }
function render() { const result=filteredJobs(); $("#jobGrid").className=`job-grid ${state.view === "list" ? "list-view" : ""}`; $("#jobGrid").innerHTML=result.map(card).join(""); $("#jobGrid").hidden=!result.length; $("#emptyState").hidden=!!result.length; $("#resultCount").textContent=result.length; $("#heroCount").textContent=result.length; $("#savedCount").textContent=state.saved.size; $("#activeChips").innerHTML=activeChips().map(chip => `<span class="active-chip">${chip}</span>`).join(""); $$("input[name=jobType]").forEach(input => input.closest(".choice").classList.toggle("active",input.checked)); }
function activeChips() { const chips=[]; if(state.type !== "전체") chips.push(state.type); state.fields.forEach(field => chips.push(field)); if(state.location !== "전체") chips.push(state.location); if(state.companyType !== "전체") chips.push(state.companyType); if(state.workMode !== "전체") chips.push(state.workMode); if(state.savedOnly) chips.push("저장한 공고"); return chips; }
function toast(message) { const el=$("#toast"); el.textContent=message; el.classList.add("show"); clearTimeout(window.toastTimer); window.toastTimer=setTimeout(() => el.classList.remove("show"),1800); }
function toggleSave(id) { state.saved.has(id) ? state.saved.delete(id) : state.saved.add(id); localStorage.setItem("finder-saved",JSON.stringify([...state.saved])); render(); toast(state.saved.has(id) ? "저장한 공고에 추가했어요." : "저장한 공고에서 삭제했어요."); }
function openJob(id) { const job=jobs.find(item => item.id === id); if(!job)return; $("#modalContent").innerHTML=`<div class="modal-top"><div><div class="modal-company"><span class="company-logo" style="background:${job.color}">${job.logo}</span><div><b>${job.company}</b><p>${job.location} · ${job.companyType}</p></div></div><h2 id="modalTitle">${job.title}</h2></div><button class="modal-apply" data-apply="${job.id}">지원하기</button></div><div class="modal-tags">${job.tags.map(tag => `<span class="tag">${tag}</span>`).join("")}</div><div class="modal-summary"><div><span>채용 형태</span><b>${job.type}</b></div><div><span>지원 자격</span><b>${job.eligibility.join(" · ")}</b></div><div><span>마감</span><b>D-${job.days}</b></div></div><section class="modal-section"><h3>주요 업무</h3><p>${job.description}</p></section><section class="modal-section"><h3>추천 이유</h3><p>공고 데이터의 업무 분야와 지원 조건을 기준으로 추천도 <b>${job.match}%</b>를 표시하고 있어요.</p></section>`; $("#modalBackdrop").hidden=false; document.body.style.overflow="hidden"; }
function closeModal() { $("#modalBackdrop").hidden=true; document.body.style.overflow=""; }
function resetFilters() { state.type="전체"; state.fields.clear(); state.location="전체"; state.companyType="전체"; state.workMode="전체"; state.eligibility="전체"; state.deadlineOnly=true; state.savedOnly=false; state.query=""; $("#searchInput").value=""; $$("input[name=jobType]").forEach(input => input.checked=input.value === "전체"); $$("input[name=field]").forEach(input => input.checked=false); ["location","companyType","workMode","eligibility"].forEach(id => $("#"+id).value="전체"); $("#deadlineOnly").checked=true; $("#savedOnly").checked=false; render(); }
$("#searchBtn").addEventListener("click",() => { state.query=$("#searchInput").value; render(); $("#finder").scrollIntoView({behavior:"smooth"}); }); $("#searchInput").addEventListener("keydown",e => { if(e.key === "Enter") $("#searchBtn").click(); });
$("#filterPanel").addEventListener("change",e => { if(e.target.name === "jobType") state.type=e.target.value; if(e.target.name === "field") e.target.checked ? state.fields.add(e.target.value) : state.fields.delete(e.target.value); if(["location","companyType","workMode","eligibility"].includes(e.target.id)) state[e.target.id]=e.target.value; if(e.target.id === "deadlineOnly") state.deadlineOnly=e.target.checked; if(e.target.id === "savedOnly") state.savedOnly=e.target.checked; render(); });
$("#resetFilters").addEventListener("click",resetFilters); $("#emptyReset").addEventListener("click",resetFilters); $("#savedNav").addEventListener("click",() => { state.savedOnly=!state.savedOnly; $("#savedOnly").checked=state.savedOnly; render(); toast(state.savedOnly ? "저장한 공고만 보고 있어요." : "전체 공고를 보고 있어요."); }); $("#openFilters").addEventListener("click",() => $("#filterPanel").classList.add("open")); $("#closeFilters").addEventListener("click",() => $("#filterPanel").classList.remove("open")); $$(".view-toggle").forEach(button => button.addEventListener("click",() => { state.view=button.dataset.view; $$(".view-toggle").forEach(item => item.classList.toggle("active",item === button)); render(); }));
$("#jobGrid").addEventListener("click",e => { const save=e.target.closest("[data-save]"); if(save){e.stopPropagation();toggleSave(Number(save.dataset.save));return;} const cardEl=e.target.closest(".job-card"); if(cardEl)openJob(Number(cardEl.dataset.id)); }); $("#jobGrid").addEventListener("keydown",e => { if((e.key === "Enter" || e.key === " ") && e.target.classList.contains("job-card")) openJob(Number(e.target.dataset.id)); }); $("#modalClose").addEventListener("click",closeModal); $("#modalBackdrop").addEventListener("click",e => { if(e.target.id === "modalBackdrop") closeModal(); const apply=e.target.closest("[data-apply]"); if(apply) toast("지원 페이지 연결을 준비 중이에요."); }); document.addEventListener("keydown",e => { if(e.key === "Escape" && !$("#modalBackdrop").hidden) closeModal(); });
render();
