let jobs = [];

const state = { type:"전체", fields:new Set(), location:"전체", companyType:"전체", workMode:"전체", eligibility:"전체", deadlineOnly:true, savedOnly:false, query:"", view:"grid", saved:new Set(JSON.parse(localStorage.getItem("finder-saved") || "[]")) };
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const esc = value => String(value ?? "").replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));
const text = value => String(value ?? "").trim();

function splitList(value) { return text(value).split(/[,|]/).map(item => item.trim()).filter(Boolean); }
function dateDays(value) { if (!/^\d{8}$/.test(text(value))) return ""; const end = new Date(`${value.slice(0,4)}-${value.slice(4,6)}-${value.slice(6,8)}T00:00:00`); return Math.ceil((end - new Date()) / 86400000); }
function normalizeJob(item, order) {
  const value = (camel, snake) => item[camel] ?? item[snake] ?? "";
  const ncs = splitList(value("ncsCdNmLst", "ncs_cd_nm_lst"));
  const hireTypes = splitList(value("hireTypeNmLst", "hire_type_nm_lst"));
  const recruitmentType = text(value("recrutSeNm", "recrut_se_nm"));
  const fields = ["연구","실험","품질"].filter(field => ncs.some(item => item.includes(field)));
  const tags = [recruitmentType, ...hireTypes, ...ncs].filter(Boolean).slice(0, 4);
  const type = recruitmentType === "신입" ? "신입" : hireTypes.some(item => item.includes("인턴")) ? "인턴" : "";
  return { id:value("recrutPblntSn", "recrut_pblnt_sn"), order, company:text(value("instNm", "inst_nm")), logo:"", color:"#202020", title:text(value("recrutPbancTtl", "recrut_pbanc_ttl")), type, fields, displayFields:ncs, location:text(value("workRgnNmLst", "work_rgn_nm_lst")), companyType:"", workMode:"", eligibility:splitList(value("acbgCondNmLst", "acbg_cond_nm_lst")), experience:recruitmentType, major:"", salary:"", days:dateDays(value("pbancEndYmd", "pbanc_end_ymd")), match:"", visual:"energy", description:"", tags, srcUrl:text(value("srcUrl", "src_url")), raw:item };
}
async function loadJobs() { const response = await fetch("/api/jobs", { cache:"no-store" }); if (!response.ok) throw new Error("Supabase 공고를 불러오지 못했어요."); jobs = (await response.json()).map(normalizeJob); render(); }
function fieldRank(job) { if (job.fields.includes("연구") && job.fields.includes("실험")) return 3; if (job.fields.includes("연구")) return 2; if (job.fields.includes("실험")) return 1; if (job.fields.includes("품질")) return 1; return 0; }
function filteredJobs() { const query=state.query.trim().toLowerCase(); return jobs.filter(job => { const searchable=[job.company,job.title,...job.fields,...job.tags].join(" ").toLowerCase(); return (state.type === "전체" || job.type === state.type) && (!state.fields.size || job.fields.some(field => state.fields.has(field))) && (state.location === "전체" || job.location === state.location) && (state.companyType === "전체" || job.companyType === state.companyType) && (state.workMode === "전체" || job.workMode === state.workMode) && (state.eligibility === "전체" || job.eligibility.includes(state.eligibility)) && (!state.deadlineOnly || (job.days !== "" && job.days >= 7)) && (!state.savedOnly || state.saved.has(job.id)) && (!query || searchable.includes(query)); }).sort((a,b) => fieldRank(b)-fieldRank(a) || a.order-b.order); }
function card(job,index) { const saved=state.saved.has(job.id); const typeLocation=[job.type,job.location].filter(Boolean).join(" · "); const eligibility=job.eligibility.join(" · "); const experienceMajor=[job.experience,job.major].filter(Boolean).join(" · "); const deadline=job.days === "" ? "" : `D-${job.days}`; return `<article class="job-card" tabindex="0" data-id="${esc(job.id)}" style="animation-delay:${index*35}ms"><div class="card-header"><div class="company-mark"><span class="company-logo" style="background:${esc(job.color)}">${esc(job.logo)}</span><span>${esc(job.company)}</span></div><button class="bookmark ${saved ? "saved" : ""}" data-save="${esc(job.id)}" aria-label="${saved ? "저장 취소" : "공고 저장"}">${saved ? "★" : "☆"}</button></div><div class="card-copy"><p class="company-line">${esc(typeLocation)}</p><h3 class="job-title">${esc(job.title)}</h3></div><div class="card-visual visual-${esc(job.visual)}"><span class="visual-word">${esc(job.displayFields.join(" · "))}</span><span class="visual-number">${String(job.id).slice(-2)}</span></div><div class="card-tags">${job.tags.map(tag => `<span class="tag">${esc(tag)}</span>`).join("")}</div><div class="card-meta"><div class="meta-item"><span>지원 자격</span><b>${esc(eligibility)}</b></div><div class="meta-item"><span>경력 · 전공</span><b>${esc(experienceMajor)}</b></div><div class="meta-item"><span>근무 방식</span><b>${esc(job.workMode)}</b></div><div class="meta-item"><span>급여</span><b>${esc(job.salary)}</b></div></div><div class="card-footer"><span class="match">추천도 <b>${esc(job.match)}</b></span><span class="deadline ${job.days !== "" && job.days<7 ? "soon" : ""}">${esc(deadline)}</span></div></article>`; }
function render() { const result=filteredJobs(); $("#jobGrid").className=`job-grid ${state.view === "list" ? "list-view" : ""}`; $("#jobGrid").innerHTML=result.map(card).join(""); $("#jobGrid").hidden=!result.length; $("#emptyState").hidden=!!result.length; $("#resultCount").textContent=result.length; $("#heroCount").textContent=result.length; $("#savedCount").textContent=state.saved.size; $("#activeChips").innerHTML=activeChips().map(chip => `<span class="active-chip">${esc(chip)}</span>`).join(""); $$('input[name=jobType]').forEach(input => input.closest('.choice').classList.toggle('active',input.checked)); }
function activeChips() { const chips=[]; if(state.type !== "전체") chips.push(state.type); state.fields.forEach(field => chips.push(field)); if(state.location !== "전체") chips.push(state.location); if(state.companyType !== "전체") chips.push(state.companyType); if(state.workMode !== "전체") chips.push(state.workMode); if(state.savedOnly) chips.push("저장한 공고"); return chips; }
function toast(message) { const el=$("#toast"); el.textContent=message; el.classList.add("show"); clearTimeout(window.toastTimer); window.toastTimer=setTimeout(() => el.classList.remove("show"),1800); }
function toggleSave(id) { state.saved.has(id) ? state.saved.delete(id) : state.saved.add(id); localStorage.setItem("finder-saved",JSON.stringify([...state.saved])); render(); toast(state.saved.has(id) ? "저장한 공고에 추가했어요." : "저장한 공고에서 삭제했어요."); }
function openJob(id) { const job=jobs.find(item => String(item.id) === String(id)); if(!job)return; const applyLink=job.srcUrl ? `<a class="modal-apply" href="${esc(job.srcUrl)}" target="_blank" rel="noopener noreferrer">공고 바로가기 ↗</a>` : ""; $("#modalContent").innerHTML=`<div class="modal-top"><div><div class="modal-company"><span class="company-logo" style="background:${esc(job.color)}">${esc(job.logo)}</span><div><b>${esc(job.company)}</b><p>${esc([job.location,job.companyType].filter(Boolean).join(" · "))}</p></div></div><h2 id="modalTitle">${esc(job.title)}</h2></div>${applyLink}</div><div class="modal-tags">${job.tags.map(tag => `<span class="tag">${esc(tag)}</span>`).join("")}</div><div class="modal-summary"><div><span>채용 형태</span><b>${esc(job.type)}</b></div><div><span>지원 자격</span><b>${esc(job.eligibility.join(" · "))}</b></div><div><span>마감</span><b>${esc(job.days === "" ? "" : `D-${job.days}`)}</b></div></div><section class="modal-section"><h3>주요 업무</h3><p>${esc(job.description)}</p></section><section class="modal-section"><h3>추천 이유</h3><p>공고 데이터의 업무 분야와 지원 조건을 기준으로 추천도 <b>${esc(job.match)}</b>를 표시하고 있어요.</p></section>`; $("#modalBackdrop").hidden=false; document.body.style.overflow="hidden"; }
function closeModal() { $("#modalBackdrop").hidden=true; document.body.style.overflow=""; }
function resetFilters() { state.type="전체"; state.fields.clear(); state.location="전체"; state.companyType="전체"; state.workMode="전체"; state.eligibility="전체"; state.deadlineOnly=true; state.savedOnly=false; state.query=""; $("#searchInput").value=""; $$('input[name=jobType]').forEach(input => input.checked=input.value === "전체"); $$('input[name=field]').forEach(input => input.checked=false); ["location","companyType","workMode","eligibility"].forEach(id => $("#"+id).value="전체"); $("#deadlineOnly").checked=true; $("#savedOnly").checked=false; render(); }

let boardPosts = [];
function formatBoardDate(value) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "" : date.toLocaleString("ko-KR", {year:"numeric", month:"numeric", day:"numeric", hour:"2-digit", minute:"2-digit"}); }
function resetBoardForm() { $("#boardPostId").value=""; $("#boardNickname").value=""; $("#boardTitleInput").value=""; $("#boardContent").value=""; $("#boardPassword").value=""; $("#boardFormTitle").textContent="새 이야기 남기기"; $("#boardSubmit").textContent="게시하기"; $("#cancelBoardEdit").hidden=true; }
function editBoardPost(post) { $("#boardPostId").value=post.id; $("#boardNickname").value=post.nickname; $("#boardTitleInput").value=post.title; $("#boardContent").value=post.content; $("#boardPassword").value=""; $("#boardFormTitle").textContent="이야기 수정하기"; $("#boardSubmit").textContent="수정하기"; $("#cancelBoardEdit").hidden=false; $("#boardForm").scrollIntoView({behavior:"smooth", block:"center"}); $("#boardPassword").focus(); }
function renderBoard() { $("#boardCount").textContent=boardPosts.length; $("#boardPosts").innerHTML=boardPosts.length ? boardPosts.map(post => `<article class="board-post"><div class="board-post-top"><div><h3>${esc(post.title)}</h3><div class="board-post-meta"><span>${esc(post.nickname || "익명")}</span><span>${esc(formatBoardDate(post.created_at))}</span></div></div><div class="board-post-actions"><button type="button" data-board-edit="${esc(post.id)}">수정</button><button type="button" data-board-delete="${esc(post.id)}">삭제</button></div></div><p class="board-post-content">${esc(post.content)}</p></article>`).join("") : `<div class="board-empty">아직 올라온 이야기가 없어요.<br />첫 고민을 남겨보세요.</div>`; }
async function loadBoard() { const response=await fetch("/api/board", {cache:"no-store"}); if(!response.ok) throw new Error("익명 게시판을 불러오지 못했어요."); boardPosts=await response.json(); renderBoard(); }
async function submitBoard(event) { event.preventDefault(); const id=$("#boardPostId").value; const payload={nickname:$("#boardNickname").value, title:$("#boardTitleInput").value, content:$("#boardContent").value, password:$("#boardPassword").value}; if(payload.password.length < 4){toast("비밀번호를 4자 이상 입력해 주세요."); return;} const button=$("#boardSubmit"); button.disabled=true; try { const response=await fetch("/api/board", {method:id ? "PATCH" : "POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(id ? {...payload,id} : payload)}); const data=await response.json().catch(() => ({})); if(!response.ok) throw new Error(data.error || "게시판 요청을 처리하지 못했어요."); resetBoardForm(); await loadBoard(); toast(id ? "게시글을 수정했어요." : "게시글을 올렸어요."); } catch(error) { toast(error.message); } finally { button.disabled=false; } }
async function deleteBoardPost(id) { const password=window.prompt("게시글 비밀번호를 입력해 주세요."); if(password === null) return; try { const response=await fetch("/api/board", {method:"DELETE", headers:{"Content-Type":"application/json"}, body:JSON.stringify({id,password})}); const data=await response.json().catch(() => ({})); if(!response.ok) throw new Error(data.error || "게시글을 삭제하지 못했어요."); await loadBoard(); toast("게시글을 삭제했어요."); } catch(error) { toast(error.message); } }

$("#searchBtn").addEventListener("click",() => { state.query=$("#searchInput").value; render(); $("#finder").scrollIntoView({behavior:"smooth"}); }); $("#searchInput").addEventListener("keydown",e => { if(e.key === "Enter") $("#searchBtn").click(); });
$("#filterPanel").addEventListener("change",e => { if(e.target.name === "jobType") state.type=e.target.value; if(e.target.name === "field") e.target.checked ? state.fields.add(e.target.value) : state.fields.delete(e.target.value); if(["location","companyType","workMode","eligibility"].includes(e.target.id)) state[e.target.id]=e.target.value; if(e.target.id === "deadlineOnly") state.deadlineOnly=e.target.checked; if(e.target.id === "savedOnly") state.savedOnly=e.target.checked; render(); });
$("#resetFilters").addEventListener("click",resetFilters); $("#emptyReset").addEventListener("click",resetFilters); $("#savedNav").addEventListener("click",() => { state.savedOnly=!state.savedOnly; $("#savedOnly").checked=state.savedOnly; render(); toast(state.savedOnly ? "저장한 공고만 보고 있어요." : "전체 공고를 보고 있어요."); }); $("#openFilters").addEventListener("click",() => $("#filterPanel").classList.add("open")); $("#closeFilters").addEventListener("click",() => $("#filterPanel").classList.remove("open")); $$(".view-toggle").forEach(button => button.addEventListener("click",() => { state.view=button.dataset.view; $$(".view-toggle").forEach(item => item.classList.toggle("active",item === button)); render(); }));
$("#jobGrid").addEventListener("click",e => { const save=e.target.closest("[data-save]"); if(save){e.stopPropagation();toggleSave(save.dataset.save);return;} const cardEl=e.target.closest(".job-card"); if(cardEl)openJob(cardEl.dataset.id); }); $("#jobGrid").addEventListener("keydown",e => { if((e.key === "Enter" || e.key === " ") && e.target.classList.contains("job-card")) openJob(e.target.dataset.id); }); $("#modalClose").addEventListener("click",closeModal); $("#modalBackdrop").addEventListener("click",e => { if(e.target.id === "modalBackdrop") closeModal(); const apply=e.target.closest("[data-apply]"); if(apply) toast("지원 페이지 연결을 준비 중이에요."); }); document.addEventListener("keydown",e => { if(e.key === "Escape" && !$("#modalBackdrop").hidden) closeModal(); });

$("#boardForm").addEventListener("submit",submitBoard); $("#newBoardPost").addEventListener("click",() => { resetBoardForm(); $("#boardForm").scrollIntoView({behavior:"smooth", block:"center"}); $("#boardTitleInput").focus(); }); $("#cancelBoardEdit").addEventListener("click",resetBoardForm); $("#boardPosts").addEventListener("click",event => { const edit=event.target.closest("[data-board-edit]"); const remove=event.target.closest("[data-board-delete]"); if(edit){ const post=boardPosts.find(item => String(item.id) === String(edit.dataset.boardEdit)); if(post) editBoardPost(post); } if(remove) deleteBoardPost(remove.dataset.boardDelete); });

render();
loadJobs().catch(error => { toast(error.message); render(); });
loadBoard().catch(error => { $("#boardPosts").innerHTML=`<div class="board-empty">${esc(error.message)}</div>`; });
